version: '3.1'

services:
  generator:
    image: my-registry:55000/gen:ci-${GENERATOR_BUILD_NUMBER-6}
    #ports: OR PORT CONFLICTS MAY RISE WHEN MULTIPLE TESTS ARE RUN IN PARALLEL 
    #  - "8080:80"
  mail:
    image: mailhog/mailhog
    #ports:
    #  - "8025:8025"
  integration:
    image: my-registry:55000/gen:integration-${BUILD_NUMBER-6}
    build: .
    environment:
      TEAMCITY_PROJECT_NAME: ${TEAMCITY_PROJECT_NAME}